info:
  description: OpenAPI specification for the import/export job engine.
  title: Job Import/Export API
  version: 1.0.0
openapi: 3.0.3
paths:
  /api/export/download/{id}:
    get:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: File download
        '404':
          description: File not found
      summary: Download export file
  /api/export/list:
    get:
      responses:
        '200':
          description: List of export job statuses
      summary: List export jobs
  /api/export/queue:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                all:
                  type: boolean
                columns:
                  items:
                    type: string
                  type: array
                file_name:
                  type: string
                format:
                  type: string
                type:
                  type: string
              required:
              - type
              type: object
        required: true
      responses:
        '200':
          description: Export job queued
      summary: Queue an export job
  /api/import/history:
    get:
      parameters:
      - in: query
        name: type
        required: true
        schema:
          type: string
      - in: query
        name: status
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Paginated history of import jobs
      summary: Get import job history
  /api/import/{type}:
    post:
      parameters:
      - description: Job type (e.g., user_import)
        in: path
        name: type
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                data:
                  items:
                    type: object
                  type: array
              required:
              - data
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                type: object
          description: Import job queued
      summary: Start an import job
  /api/job-types:
    get:
      responses:
        '200':
          description: List of job types
      summary: List available job types
